config/routes.rb
CreativesApp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'creatives#index'
  get 'tags', to: 'tags#index'

  resources :creatives do
    resources :chapters
    resource :comments
    resources :pictures
  end

  get '/:search' => 'creatives#index', :as => :search
  post 'creatives/:id/reorder' => 'creatives#reorder', :as => :reorder
  get 'creatives/:id/read' => 'creatives#read', :as => :read_creative
  post 'creatives/:creative_id/pictures/:id/crop' => 'pictures#crop', :as => :crop_picture
  post 'creatives/:creative_id/pictures/:id/revert' => 'pictures#revert', :as => :revert_original
  post 'creatives/:id/mistake' => 'creatives#mistake', :as => :mistake_creative

  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'users/:id' => 'users#show', :as => :user


end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id          :integer          not null, primary key
#  created_at  :datetime
#  updated_at  :datetime
#  creative_id :integer
#  file        :string(255)
#  cropped     :boolean
#

class Picture < ActiveRecord::Base
  mount_uploader :file, FileUploader
  belongs_to :creative, :inverse_of => :pictures
  
  has_many :tags, :through => :taggings
  has_many :taggings, :as => :taggable  
  attr_reader :tag_tokens, :cropped_url

  def tag_tokens=(ids)
    self.tag_ids = Tag.ids_from_tokens(ids)
  end

  def cropped_url
    self.file.url + ".cropped.jpg"
  end

  def thumb_cropped_url
    self.file.thumb.url + ".cropped.jpg"
  end
  
  def to_jq_upload
    {
      "name" => read_attribute(:file),
      "size" => file.size,
      "url" => file.url,
      "edit_url" => "/creatives/#{creative_id}/pictures/#{id}/edit",
      "delete_url" => "/creatives/#{creative_id}/pictures/#{id}",
      "delete_type" => "DELETE"
    }
  end
  
  def to_jq_download
    {
      "id" => id,
      "name" => read_attribute(:file),
      "size" => file.size,
      "cropped" => cropped,
      "cropped_url" => cropped_url,
      "cropped_thumbnail_url" => thumb_cropped_url,
      "url" => file.url,
      "thumbnail_url" => file.thumb.url,
      "edit_url" => "/creatives/#{creative_id}/pictures/#{id}/edit",
      "delete_url" => "/creatives/#{creative_id}/pictures/#{id}",
      "delete_type" => "DELETE"

    }
  end
end

app/controllers/pictures_controller.rb
require 'RMagick'
include Magick
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :destroy, :crop, :revert]
  before_filter :authenticate_user!

  # GET /pictures
  # GET /pictures.json
  def index
    @creative = Creative.find(params[:creative_id])
    @pictures = @creative.pictures.load
    @picture = Picture.new

    respond_to do |format|
      format.html # index.html.erb
      # format.json { render json: @pictures }
      format.json { render json: @pictures.map{|pic| pic.to_jq_download } }
    end
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    #binding.pry
    creative = Creative.find(params[:creative_id])
    @picture = creative.pictures.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html {
          render :json => [@picture.to_jq_download].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render json: {files: [@picture.to_jq_download]}, status: :created, location: creative_picture_path(creative, @picture) }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end
  def crop
    par = picture_params_without_picture
    target = Dir.pwd+"/public"+@picture.cropped_url
    target_thumb = Dir.pwd+"/public"+@picture.thumb_cropped_url
    if par[:original] == "true"
      source = Dir.pwd+"/public"+@picture.file.url
      @picture.update_attribute(:cropped, true)
    else
      source = target
    end
    image = Image.read(source).first
    new_image = image.crop!(par[:x].to_i,par[:y].to_i,par[:w].to_i,par[:h].to_i)
    new_image.write(target)

    thumb = Image.read(target).first.resize_to_fill 200, 150
    thumb.write(target_thumb)
  end

  def revert
    target = Dir.pwd+"/public"+@picture.cropped_url
    target_thumb = Dir.pwd+"/public"+@picture.thumb_cropped_url
    File.delete(target) if File.exist?(target)
    File.delete(target_thumb) if File.exist?(target_thumb)
    @picture.update_attribute(:cropped, false)
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to creative_pictures_path(@picture.creative), notice: 'Picture was successfully updated.' }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to creative_pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      #binding.pry
      params.require(:picture).permit(:file, :tag_tokens, :x, :y, :w, :h)
    end

    def picture_params_without_picture
      #binding.pry
      params.permit(:id, :creative_id, :file, :tag_tokens, :x, :y, :w, :h,:original, :image)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_ret.html.erb
<%= @picture.cropped ? (image_tag(@picture.cropped_url, :id => "example")) : (image_tag(@picture.file.url, :id => "example")) %>
<div id="Filters">
  <div class="Filter">
    <div class="FilterName">
      <p><%= t('brightness')%></p>
    </div>
    <div class="FilterSetting">
      <input type="range" min="-100" max="100" step="1" value="0" data-filter="brightness">
      <span class="FilterValue">0</span>
    </div>
  </div>
  <div class="Filter">
    <div class="FilterName">
      <p><%= t('contrast')%></p>
    </div>
    <div class="FilterSetting">
      <input type="range" min="-100" max="100" step="1" value="0" data-filter="contrast" >
      <span class="FilterValue">0</span>
    </div>
  </div>
</div>

app/views/pictures/_template_download.html.erb
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <li class="template-download" style="text-align:center;">
      {% if (file.error) { %}
        <p class="name"><span>{%=file.name%}</span></p>
        <p class="size"><span>{%=o.formatFileSize(file.size)%}</span></p>
        <p class="error" colspan="2"><span class="label alert radius">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</p>
        {% } else { %}
        <p class="preview">
          {% if (file.thumbnail_url) { %}
            {% if (file.cropped) { %}
              <a href="{%=file.edit_url%}">
                <img class="th" src="{%=file.cropped_thumbnail_url%}">
              </a>
            {% } else { %}
              <a href="{%=file.edit_url%}">
                <img class="th" src="{%=file.thumbnail_url%}">
              </a>
            {% } %}
          {% } %}
        </p>
        <p class="delete">
          <button class="tiny secondary" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}" data-confirm="<%= t('are_you_sure')%>" >
            <%= t('.removepic')%>
          </button>
        </p>
       {% } %}
    </li>
  {% } %}
</script>

app/views/pictures/_template_upload.html.erb
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <li class="template-upload fade" style="text-align:center;">
    <p class="preview"><span class="fade"></span></p>
    {% if (file.error) { %}
    <p class="error"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</p>
    {% } else if (o.files.valid && !i) { %}
    <p>
      <div class="progress alert"><div class="bar meter" style="width:0%;"></div></div>
    </p>
<div class="button-group">
    <p class="start">{% if (!o.options.autoUpload) { %}
      <button class="tiny">
        <span><%=t("upload") %></span>
      </button>
      {% } %}</p>
    {% } else { %}
    <p colspan="2"></p>
    {% } %}
    <p class="cancel">{% if (!i) { %}
      <button class="tiny alert">
        <span><%=t("cancel") %></span>
      </button>
      {% } %}</p>
</div>
  </li>
  {% } %}
</script>

app/views/pictures/crop.js.erb
var updatevalues;
updatevalues = function(c) {
  var par;
  par = "?x=" + c.x + "&y=" + c.y + "&w=" + c.w + "&h=" + c.h;
  $("#croppic").attr('data-params',par);
};

$("#pic_container_<%= @picture.id %>").html("<img id='target-<%= @picture.id%>'>");
$('#target-<%= @picture.id %>').attr('src','<%= @picture.cropped_url%>'+"?"+new Date())
$('#target-<%= @picture.id %>').Jcrop({
				      onChange:   updatevalues
				    });
$('#croppic').attr('data-original','false');

app/views/pictures/edit.html.erb
<%= javascript_include_tag "jquery.Jcrop.min.js" %>
<%= stylesheet_link_tag "jquery.Jcrop.min.css" %>
<fieldset>
<legend><h1><%= link_to "", creative_pictures_path, :class => "foundicon-left-arrow"%><%= t('.title')%></h1></legend>
  <%= form_for(@picture, :url => creative_picture_path(@picture.creative, @picture), :remote => true) do |f| %>
  <%= f.text_field :tag_tokens, "data-pre" => @picture.tags.map(&:attributes).to_json %>
      <input class="button radius" type='submit' value="<%= t("save") %>"/>
  <% end %>
  <dl class="tabs" data-tab>
    <dd class="active"><a href="#panel-crop-<%= @picture.id %>"><%= t('.crop')%></a></dd>
  </dl>
  <div class="tabs-content">
    <div class="content active" id="panel-crop-<%= @picture.id %>">
      <div id="pic_container_<%= @picture.id %>">
        <%= @picture.cropped ? (image_tag(@picture.cropped_url, :id => "target-#{@picture.id}")) : (image_tag(@picture.file.url, :id => "target-#{@picture.id}")) %>
      </div>
      <script type="text/javascript">
          jQuery(function($){
            var updatevalues;
            updatevalues = function(c) {
						  var par;
						  par = "?x=" + c.x + "&y=" + c.y + "&w=" + c.w + "&h=" + c.h;
						  //alert(par);
						  $("#croppic").attr('data-params',par);
						};
						$('#target-<%= @picture.id %>').Jcrop({
				      onChange:   updatevalues
				    });
          });
      </script>
      <button id="croppic" data-url="<%= crop_picture_path(@picture.creative, @picture) %>" data-original="<%= !@picture.cropped %>" data-id="<%= @picture.id %>" data-params=""><%= t(".croping") %></button>
      <button id="change_source_to_crop" data-url="<%= @picture.file.url+'.cropped.jpg' %>" data-original="false" data-id="<%= @picture.id %>"><%= t(".show_cropped") %></button>
      <button id="change_source_to_original" data-url="<%= @picture.file.url %>" data-original="true" data-id="<%= @picture.id %>"><%= t(".show_original") %></button>
      <button id="revert_original" data-url="<%= revert_original_path(@picture.creative, @picture) %>" data-id="<%= @picture.id %>"><%= t(".revert_original") %></button>
    </div>
  </div>
</fieldset>

app/views/pictures/index.html.erb
<%= form_for @picture, :url => creative_pictures_path, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
  <div class="button-group round">
      <%= link_to "", creative_path(@creative), :class => "button secondary foundicon-left-arrow" %>
    <span class="button fileinput-button success">
      <span><%=t(".add_files") %></span>
      <%= f.file_field :file, multiple: true, id: 'upload-field' %>
    </span>
    <span id="upload_all" class="button success"><%=t(".upload_all") %></span>

  </div>
  <div class="presentation">
    <ul class="files small-block-grid-2 medium-block-grid-3 large-block-grid-4">
    </ul>
  </div>
<% end %>

<%= render 'template_upload' %>
<%= render 'template_download' %>

app/views/pictures/retouch.js.erb
var updatevalues;
updatevalues = function(c) {
  var par;
  par = "?x=" + c.x + "&y=" + c.y + "&w=" + c.w + "&h=" + c.h;
  $("#croppic").attr('data-params',par);
};

$("#pic_container_<%= @picture.id %>").html("<img id='target-<%= @picture.id%>'>");
$('#target-<%= @picture.id %>').attr('src','<%= @picture.file.url%>'+".cropped.jpg?"+new Date())
$('#target-<%= @picture.id %>').Jcrop({
				      onChange:   updatevalues
				    });
$('#croppic').attr('data-original','false');

app/views/pictures/revert.js.erb
var updatevalues;
updatevalues = function(c) {
  var par;
  par = "?x=" + c.x + "&y=" + c.y + "&w=" + c.w + "&h=" + c.h;
  $("#croppic").attr('data-params',par);
};

$("#pic_container_<%= @picture.id %>").html("<img id='target-<%= @picture.id%>'>");
$('#target-<%= @picture.id %>').attr('src','<%= @picture.file.url%>'+"?"+new Date())
$('#target-<%= @picture.id %>').Jcrop({
				      onChange:   updatevalues
				    });
$('#croppic').attr('data-original','true');
$('#retpicplace').html('<%= j render "ret" %>');
alert("<%= t('.source_restored')%>")

app/views/pictures/update.js.erb
alert("Теги обновлены");