config/routes.rb
CreativesApp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'creatives#index'
  get 'tags', to: 'tags#index'

  resources :creatives do
    resources :chapters
    resource :comments
    resources :pictures
  end

  get '/:search' => 'creatives#index', :as => :search
  post 'creatives/:id/reorder' => 'creatives#reorder', :as => :reorder
  get 'creatives/:id/read' => 'creatives#read', :as => :read_creative
  post 'creatives/:creative_id/pictures/:id/crop' => 'pictures#crop', :as => :crop_picture
  post 'creatives/:creative_id/pictures/:id/revert' => 'pictures#revert', :as => :revert_original
  post 'creatives/:id/mistake' => 'creatives#mistake', :as => :mistake_creative

  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'users/:id' => 'users#show', :as => :user


end

app/models/creative.rb
# == Schema Information
#
# Table name: creatives
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Creative < ActiveRecord::Base
	has_many :chapters, :dependent => :destroy, :inverse_of => :creative
	has_many :comments, :dependent => :destroy
  has_many :pictures, :dependent => :destroy, :inverse_of => :creative
	
	has_many :tags, :through => :taggings
	has_many :taggings, :as => :taggable
	has_many :mistakes

	belongs_to :user
	has_many :readings
	has_many :readers, through: :readings, :source => :user

	attr_reader :tag_tokens

  def author?(user)
    self.user == user
  end
 
	def tag_tokens=(ids)
		self.tag_ids = Tag.ids_from_tokens(ids)
  end

  def parent
    self
  end
  

end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  before_action :set_creative, :only => [:show, :edit, :update, :destroy, :reorder, :read, :mistake]
  before_filter :authenticate_user!, :only => [:edit, :update, :destroy, :new]

  def index
    search_string = search_params[:search]
    if search_string.present?
      results = ThinkingSphinx.search "*#{search_string}*", :classes => [Creative,Chapter,Tag], :match_mode => :any
      @creatives = results.map {|result| result.parent}
      @creatives.flatten!
      @creatives.uniq!
      @creatives.compact!
      @title = @creatives.empty? ? (t('.search_title_not_found') + search_string) : t('.search_title')
    else
      @creatives = Creative.all
      @title = t(".all_creatives")
    end
  end

  # GET /creatives/1
  # GET /creatives/1.json
  def show
    @chapters = @creative.chapters.order(number: :asc)
    @creative.readers.delete current_user if current_user.present?
    check_for_mistakes
  end
  # GET /creatives/new
  def new
    @creative = Creative.new
  end

  # GET /creatives/1/edit
  def edit
  end

  def mistake
    @creative.mistakes.create(mistake_params)
  end

  # POST /creatives
  # POST /creatives.json
  def create
    @creative = current_user.creatives.new(creative_params)

    respond_to do |format|
      if @creative.save
        format.html { redirect_to @creative, notice: t('.created_notice') }
        format.json { render action: 'show', status: :created, location: @creative }
      else
        format.html { render action: 'new' }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end
  def read
    @chapters = @creative.chapters.order(number: :asc)
    @creative.readers << current_user if !@creative.readers.include?(current_user) && current_user
  end

  def reorder
    chapter_ids = params[:sorted].split(',')
    chapter_ids.each_with_index do |chapter_id, i|
      chapter = Chapter.find(chapter_id)
      chapter.update_attribute(:number, i)
    end
    render :nothing => true
  end

  # PATCH/PUT /creatives/1
  # PATCH/PUT /creatives/1.json
  def update
    respond_to do |format|
      if @creative.update(creative_params)
        format.html { redirect_to @creative, notice: t('.updated_notice') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatives/1
  # DELETE /creatives/1.json
  def destroy
    @creative.destroy
    respond_to do |format|
      format.html { redirect_to creatives_url }
      format.json { head :no_content }
    end
  end

  private

    def check_for_mistakes
      @creative.mistakes.each do |mistake|
        @creative.chapters.each do |chapter|
          mistake.destroy if !chapter.body.include?(mistake.mistake_text)
        end
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_creative
      @creative = Creative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creative_params
      params.require(:creative).permit(:name, :description, :user_id, :tag_tokens)
    end

    def mistake_params
      params.permit(:mistake_text)
    end

    def search_params
      params.permit(:search)
    end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/views/creatives/_distance.html.erb
<% @creative.readers.each do |reader| %>
  <p id="near_<%=reader.id%>"></p>
  <script type="text/javascript">
  <% if current_user != reader && current_user %>
    var glatlng1 = new GLatLng(<%= current_user.user_city[0]%>, <%= current_user.user_city[1]%>);
    var glatlng2 = new GLatLng(<%= reader.user_city[0]%>, <%= reader.user_city[1]%>);
    var miledistance = glatlng1.distanceFrom(glatlng2, 3959).toFixed(1);
    var kmdistance = (miledistance * 1.609344).toFixed(1);
    if(kmdistance < 100) {
    	document.getElementById('near_<%=reader.id%>').innerHTML = kmdistance + ' kilometers' + ":" + "<%= j link_to (reader.nickname.present? ? reader.nickname : reader.email), user_path(reader) %>";
		}
    <% end %>
  </script>
<%end%>
<%= t(".nobody_reads") if @creative.readers.empty? %>

app/views/creatives/_mistake.html.erb
<fieldset class="mistakes">
  <legend><h2><%= t("mistakes")%></h2></legend>
  <ul> 
    <% @creative.mistakes.each do |mistake| %>
      <li class="mistakes">
        <span> 
          <%= t("added")%> <%= I18n.localize(mistake.created_at) %>:&nbsp;&nbsp;
        </span>
        <span>
          <%= mistake.mistake_text %>
        </span> 
      </li>  
    <% end %>
  </ul>
</fieldset>

app/views/creatives/_mistakes.html.erb
<fieldset class="mistakes">
  <legend><h2><%= t('mistakes')%></h2></legend>
  <ul> 
    <% @creative.mistakes.each do |mistake| %>
      <li class="mistakes">
        <span> 
          <%= t('added')%> <%= I18n.localize(mistake.created_at) %>:&nbsp;&nbsp;
        </span>
        <span>
          <%= mistake.mistake_text %>
        </span> 
      </li>  
    <% end %>
  </ul>
</fieldset>

app/views/creatives/index.html.erb
<% content_for :title, @creative ? @creative.name : t(".all_creatives") %>

<h1 class="medium-12 columns"><%= @title%></h1>
<% @creatives.each do |creative| %>
  <div class="medium-6 columns">
    <div class="panel">
      <% if creative.author?(current_user) %>
        <%= link_to "", creative, :method => :delete, data: { confirm: t('.are_you_sure')}, :class => "foundicon-trash right" %>
      <% end %>      
      <h3><%= link_to creative.name, creative %></h3>
      <%= tag_list(creative) %>
      <br/>
      <%= creative.description %>
      <p><%=t(".chapters")%> <%= creative.chapters.size %></p>
      <ul class="button-group radius">
        <%= link_to t('.read'), read_creative_path(creative, :anchor => "chapter_last"),:class => "right foundicon-right-arrow" %>
      </ul>
    </div>          
  </div>
<% end %>
<div class="medium-6 columns">
  <h1><%= link_to '', new_creative_path, class: "foundicon-plus" if current_user %></h1>
</div>

app/views/creatives/mistake.js.erb
alert("<%=t('mistake_sent')%>");

app/views/creatives/new.html.erb
<h1>
  <%= link_to "", creatives_path, :class => "foundicon-left-arrow left medium" %>
  <%= t('.title')%>
</h1>
<br><br><br><br>
<%= form_for(@creative) do |f| %>
  <% if @creative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creative.errors.count, "error") %> prohibited this creative from being saved:</h2>
      <ul>
        <% @creative.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :name, class: "right inline"%>
    </div>
    <div class="small-9 columns">
      <%= f.text_field :name, :required => "" %>
    </div>
  </div>
  <div class="row">
    <div class="small-3 columns">
      <%= f.label :description, class: "right inline"%>
    </div>
    <div class="small-9 columns">
      <%= f.text_area :description %>
    </div> 
  </div>
  <div class="small-3 columns">
    <label class="right inline"><%= t('tags')%></label>
  </div>
  <div class="small-9 columns">
    <%= f.text_field :tag_tokens %> 
  </div>
    <div class="small-9 small-offset-3 columns">
      <button type="submit" class="button success radius right"><%= t('.create')%></button>
    </div>
<% end %>

app/views/creatives/read.html.erb
    <script src="http://maps.google.com/maps?file=api&v=2&key=ABQIAAAA7j_Q-rshuWkc8HyFI4V2HxQYPm-xtd00hTQOC0OXpAMO40FHAxT29dNBGfxqMPq5zwdeiDSHEPL89A" type="text/javascript"></script>
<div id="home"></div>
<div data-magellan-expedition="fixed" align="center">
  <dl class="sub-nav">
  <div class="row">
    <div class="large-9 large-centered medium-12 medium-centered column">
      <dd><%= link_to 'Вернуться к креативу', creative_path(@creative), :class => "left" %></dd>
      <dd>|</dd>
      <dd data-magellan-arrival="home"><a href="#home"><%= t('.to_top')%></a></dd>
      <dd>|</dd>
      <dd><a id="plustext">(+)</a></dd>
      <dd><a id="minustext">(-)</a></dd>
      <dd>|</dd>
      <% @chapters.each do |chapter| %>
        <dd data-magellan-arrival="chapter_<%= chapter.number+1 %>"><%= link_to chapter.name, :anchor => "chapter_#{chapter.number+1}" %></dd>
      <% end %>
      <dd><span id="current">yyy</span></dd>
    </div>
    </div>
  </dl>
</div>
<%= render 'distance' %>
<fieldset>
  <legend align="center">
    <h2 id="chapter-read" data-url="<%= mistake_creative_path(@creative)%>">
      <%= @creative.name %>
    </h2>
  </legend>
  <div>
    <%= t('.short_desc')%><%= @creative.description %>
  </div>
  <% @chapters.each do |chapter| %>
    <fieldset>
      <legend align="center" data-magellan-destination="chapter_<%= chapter.number+1 %>"><h3 id="chapter_<%= chapter.number+1 %>"><%= chapter.name %></h3></legend>
        <div class="markdown-source"> <%= chapter.body %></div>
    </fieldset>
  <% end %>
</fieldset>

app/views/creatives/show.html.erb
<div class="creative row" data-comments=<%= creative_comments_path(@creative) %>>
  <fieldset class="medium-12 columns">
    <legend>
      <h2><%= best_in_place_if @creative.author?(current_user), @creative, :name, :type => :input, :required => true, :activator => "#editme"%><a id="editme" class="foundicon-edit right" href="#"></a></h2>
    </legend>
    <h5><%= best_in_place @creative, :description, :nil => "click me", :type => :textarea %></h5>
    <% if @creative.author?(current_user) %>
      <%= form_for @creative, :remote => true do |f| %>
        <ul>
          <button class="foundicon-checkmark secondary right" type="submit"></button>
          <%= f.text_field :tag_tokens, "data-pre" => @creative.tags.map(&:attributes).to_json %>
        </ul>
      <% end %>
    <% else %>
      <%= tag_list(@creative) %>
    <% end %>
    <h3><span class="right"><%= link_to @creative.user.nickname.present? ? @creative.user.nickname : @creative.user.email, @creative.user %></span></h3>
  </fieldset>

  <% if @creative.author?(current_user) && @creative.mistakes.present? %>
    <%= render 'mistakes' %>
  <% end %>
  <h1 class="row">
    <span class="small-5 columns">
      <%= link_to "", creatives_path, :class => "foundicon-left-arrow" %>
    </span>
    <span class="small-1 small-centered columns">
      <%= link_to "", new_creative_chapter_path(@creative), :class => "foundicon-add-doc" if  @creative.author?(current_user) %>
    </span>
    <span class="small-6 columns">
      <%= link_to(read_creative_path(@creative),:class => "right") do%>
          <%= t(".read") %> <i class="foundicon-right-arrow"></i>
      <% end %>
    </span>
  </h1>
  <div id="sortable-grid" class="small-block-grid-1 medium-block-grid-2 large-block-grid-4" data-url="<%= reorder_path(@creative) %>">
    <% @chapters.each do |chapter| %>
      <li id="<%= chapter.id %>">
          <div class="th panel chapter-item">
            <ul class='button-group right'>
              <% if @creative.author?(current_user) %>
                <%= link_to "", edit_creative_chapter_path(@creative, chapter), :class => "foundicon-tools" %>
                <%= link_to "", creative_chapter_path(@creative, chapter), method: :delete, data: { confirm: "are you sure?" }, :class => "foundicon-trash" %>
              <% end %>
            </ul>
              <p><b><%= link_to chapter.name, read_creative_path(@creative, :anchor => "chapter_#{chapter.number+1}"), :class => "black foundicon-right-arrow" %></h3></b></p>
              <p class="markdown-source"><%= chapter.body %></p>
          </div>
      </li>
    <% end %>
  </div>
</div>
  <br><br><br><br>
<% unless @creative.pictures.empty? %>
  <ul class="clearing-thumbs" data-clearing>
    <% @creative.pictures.each do |picture| %>
      <li>
        <a class="th" href="<%= picture.cropped ? picture.cropped_url : picture.file.url %>">
          <img data-caption="<%= tag_list_raw(picture) %>" src="<%= picture.cropped ? picture.thumb_cropped_url : picture.file.thumb.url %>">
        </a>
      </li>
    <% end %>
  </ul>
<% else %>
  <p> <%= t(".no_pictures") %> </p>
<% end %>
<br>
<div class="right">
  <%= link_to t(".manage-pictures"), creative_pictures_path(@creative), :class => "small button secondary" if @creative.author?(current_user) %>
</div>
<br><br><br><br>
<%= render 'comments/show' %>
<%= render 'comments/form' %>