config/routes.rb
CreativesApp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'creatives#index'
  get 'tags', to: 'tags#index'

  resources :creatives do
    resources :chapters
    resource :comments
    resources :pictures
  end

  get '/:search' => 'creatives#index', :as => :search
  post 'creatives/:id/reorder' => 'creatives#reorder', :as => :reorder
  get 'creatives/:id/read' => 'creatives#read', :as => :read_creative
  post 'creatives/:creative_id/pictures/:id/crop' => 'pictures#crop', :as => :crop_picture
  post 'creatives/:creative_id/pictures/:id/revert' => 'pictures#revert', :as => :revert_original
  post 'creatives/:id/mistake' => 'creatives#mistake', :as => :mistake_creative

  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'users/:id' => 'users#show', :as => :user


end

app/models/chapter.rb
# == Schema Information
#
# Table name: chapters
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  number      :integer
#  body        :text
#  creative_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Chapter < ActiveRecord::Base
	belongs_to :creative, :inverse_of  => :chapters

	def parent
    self.creative
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_creative_chapter, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:edit, :update, :destroy, :new]

  def index
    @chapters = Chapter.all
  end

  def new
    @chapter = Chapter.new
    @chapter.creative_id = params[:creative_id]
  end

  def create
    @chapter = Chapter.new(chapter_params)
    @chapter.number = @chapter.creative.chapters.count + 1;

      if @chapter.save
        redirect_to @chapter.creative, notice: t(".created_notice")
      else
        render action 'new'
      end
  end

  def update
    if @chapter.update(chapter_params)
      redirect_to @chapter.creative, notice: t(".updated_notice")
    else
      render action: 'update'
    end
  end

  def destroy
    creative_id = @chapter.creative_id
    @chapter.destroy
    redirect_to creative_path(creative_id)
  end

  private

  def set_creative_chapter
    @chapter = Chapter.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:name, :number, :body, :creative_id)
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_modal_pictures.html.erb
<div id="choosePicModal" class="reveal-modal" data-reveal>
  <h2><%= t('.choose_pics')%></h2>
  <ul class="small-block-grid-3 medium-block-grid-6 large-block-grid-8">
    <% if @chapter.creative.pictures.empty? %>
      <%= content_tag :h3, t('.no_pictures') %>
    <% else %>
      <% @chapter.creative.pictures.each do |pic| %>
        <li><img class ="addimagebutton th" src="<%= pic.cropped? ? pic.thumb_cropped_url : pic.file.thumb.url %>" url="<%= pic.cropped? ? pic.cropped_url : pic.file.url %>"></li>
      <% end %>
    <% end %>
  </ul>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/chapters/edit.html.erb
<div class="chapter">
  <div>
    <h1>
      <%= link_to '', creative_path(@chapter.creative), :class=> "foundicon-left-arrow" %>
      <%= t(".editing_chapter") %><i class="foundicon-checkmark hidden right"></i>
    </h1> 
  </div>
  <fieldset>
    <%= form_for @chapter, url: creative_chapter_path(@chapter.creative, @chapter), :html => { :class => "chapter_save"}, :remote => true do |f| %>
      <% if @chapter.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>
          <ul>
            <% @chapter.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.text_field :name, :required => "" %>
      </div>
      <div class="row">
        <div class="medium-6 columns">
          <div class='wmd-panel'>
            <div id='wmd-button-bar'></div>
            <%= text_area_tag :body, @chapter.body, :name => "chapter[body]", :class => "wmd-input", :id => "wmd-input" %>
          </div>
        </div>
        <div class="medium-6 columns">
        <div class="small button radius" data-reveal-id="choosePicModal"><%= t(".insert_picture") %></div>
          <p><%= t(".preview") %></p>
          <div id="wmd-preview" class="wmd-panel wmd-preview"></div>
        </div>
      </div>
  </fieldset>
  <%= f.hidden_field :creative_id %>
  <%= f.hidden_field :number %>
  <button type="submit" class="submit-chapter success right foundicon-checkmark"> <%= t("save") %></button>
    <% end %>
</div>  
<%= render "modal_pictures" %>

app/views/chapters/new.html.erb
<div class='chapter'>
  <div>
    <h1><%= link_to '', creative_path(@chapter.creative), :class=> "foundicon-left-arrow" %><%= t(".new_chapter")%></h1>
  </div>
  <fieldset>
    <%= form_for @chapter, url: creative_chapters_path do |f| %>
      <% if @chapter.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this section from being saved:</h2>
          <ul>
            <% @chapter.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :name, :placeholder => t(".chapter_name"), :required => "" %>
        <div  class="row">
          <div class="medium-6 columns">
            <div class='wmd-panel'>
              <div id='wmd-button-bar'></div>
              <%= text_area_tag :body, @chapter.body, :name => "chapter[body]", :class => "wmd-input", :id => "wmd-input" %>
            </div>
          </div>
          <div class="medium-6 columns">
            <div class="small button radius addbtn" value="#Заголовок#" data-reveal-id="choosePicModal"><%= t(".insert_picture") %></div>
            <p><%= t(".preview") %></p>
            <div id="wmd-preview" class="wmd-panel wmd-preview"></div>
          </div>
        </div>
  </fieldset>
    <%= f.hidden_field :creative_id %>
    <button type="submit" class="success foundicon-checkmark right"><%= t("save") %> </button>
    <% end %>
</div>
<%= render "modal_pictures" %>