config/routes.rb
CreativesApp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'creatives#index'
  get 'tags', to: 'tags#index'

  resources :creatives do
    resources :chapters
    resource :comments
    resources :pictures
  end

  get '/:search' => 'creatives#index', :as => :search
  post 'creatives/:id/reorder' => 'creatives#reorder', :as => :reorder
  get 'creatives/:id/read' => 'creatives#read', :as => :read_creative
  post 'creatives/:creative_id/pictures/:id/crop' => 'pictures#crop', :as => :crop_picture
  post 'creatives/:creative_id/pictures/:id/revert' => 'pictures#revert', :as => :revert_original
  post 'creatives/:id/mistake' => 'creatives#mistake', :as => :mistake_creative

  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'users/:id' => 'users#show', :as => :user


end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round fixed-alert <%= name == :notice ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to (t'creatives.title'), root_path %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a><span><%=t 'menu'%></span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
    	<%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to (t'logout'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to (t'login'), new_user_session_path %></li>
<% end %>
<li class="divider"></li>
<% if user_signed_in? %>
  <li><%= link_to (t'edit_account'), edit_user_registration_path %></li>
<% else %>
  <li><%= link_to (t'sign_up'), new_user_registration_path %></li>
<% end %>
<li class="divider"></li>
<% if current_user.try(:admin) %>
  <li><%= link_to (t'users'), users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "креативы" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Креативы" %>">
    <%= stylesheet_link_tag "application" %>
    <%# Foundation 5.0.2 won't work with Rails Turbolinks %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
        <%= render 'layouts/messages' %>
    <div class="row main-row">
      <%= javascript_include_tag "application" %>
      <p/>
      <div class="medium-7 medium-centered large-5 large-centered columns">
        <form action="<%= root_path %>" method="get" >
          <div class="row collapse">
            <div class="small-9 columns">
              <%= text_field_tag :search, params[:search], :required => "", :placeholder => "Введите запрос" %>  
            </div>
            <div class="small-3 columns">
              <%= submit_tag t('search'), :name => nil, :class => "button postfix" %>
            </div>
          </div>
        </form> 
      </div>
      <div class="small-11 small-centered medium-11 medium-centered large-10 large-centered columns">
        <%= yield %>
      </div>
      <%= javascript_include_tag "app-after" %>
    </div>
  </body>
</html>